package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"text/template"
)

const versionTemplate = `// Code generated by tools/genversion. DO NOT EDIT.

package version

// Version information populated at build time
const (
	Version = "{{ .Version }}"
	Commit  = "{{ .Commit }}"
	Date    = "{{ .Date }}"
)
`

type VersionInfo struct {
	Version string
	Commit  string
	Date    string
}

func getGitCommit() string {
	cmd := exec.Command("git", "rev-parse", "--short", "HEAD")
	output, err := cmd.Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(output))
}

func getGitDate() string {
	cmd := exec.Command("git", "log", "-1", "--format=%ct")
	output, err := cmd.Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(output))
}

func isGitDirty() bool {
	cmd := exec.Command("git", "diff-index", "--quiet", "HEAD", "--")
	err := cmd.Run()
	return err != nil
}

func main() {
	commit := getGitCommit()
	date := getGitDate()

	baseVersion := "11.0.23"
	version := baseVersion

	if commit != "unknown" {
		if isGitDirty() {
			version = fmt.Sprintf("%s-dev+%s", baseVersion, commit)
		} else {
			version = fmt.Sprintf("%s+%s", baseVersion, commit)
		}
	}

	info := VersionInfo{
		Version: version,
		Commit:  commit,
		Date:    date,
	}

	tmpl, err := template.New("version").Parse(versionTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	file, err := os.Create("internal/version/version.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating version file: %v\n", err)
		os.Exit(1)
	}
	defer file.Close() // nolint:errcheck

	err = tmpl.Execute(file, info)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1) // nolint:gocritic
	}

	fmt.Printf("Generated version.go with version: %s\n", version)
}
