#!/bin/bash

set -o errexit
set -o nounset

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 messages.txt" >&2
  exit 1
fi

export LANG=C

cat <<'EOT'
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by gen-text.sh - DO NOT EDIT.$

//nolint:all

package text

type MsgNum int32

EOT

toolsdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
awk -f "${toolsdir}/gen-text.awk" <"$1"
perl -- "${toolsdir}/gen-text.pl" <"$1"
