package parser

import (
	"github.com/nosborn/federation-1999/internal/model"
	"github.com/nosborn/federation-1999/pkg/ibgames"
)

type CommandExecutor interface {
	CmdAcceptFactory()
	CmdAcceptJob(jobNo int32)
	CmdAct(action string)
	CmdAdd(bayList *BayList, planetName string)
	CmdAlarm(minutes int32)
	CmdAlarmOff()
	CmdAllocate(points int32, commodity model.Commodity)
	CmdAllocateSocialSecurity(points int32)
	CmdAutomatic()
	CmdBang()
	CmdBash()
	CmdBlast(what, with model.Name)
	CmdBlessHostess(name string)
	CmdBlessSenator(name string)
	CmdBribe(amount int32)
	CmdBribeTechnician()
	CmdBrief()
	CmdBroadcast(message string)
	CmdBuild(project model.Project)
	CmdBump(name string)
	CmdBuyAle()
	CmdBuyAmmunition(number int32)
	CmdBuyClothes(clothes string)
	CmdBuyCompany(name string)
	CmdBuyDexterity(points int32)
	CmdBuyFactory(where string, commodity model.Commodity)
	CmdBuyFood()
	CmdBuyFuel(quantity int32)
	CmdBuyGoods(commodity model.Commodity, planetName string, quantity int32)
	CmdBuyIntelligence(points int32)
	CmdBuyLamp()
	CmdBuyMissiles(number int32)
	CmdBuyPizza()
	CmdBuyRound(description string)
	CmdBuySpyBeam()
	CmdBuySpyScreen()
	CmdBuyStamina(points int32)
	CmdBuyStrength(points int32)
	CmdBuyWarehouse()
	CmdChange()
	CmdCheat()
	CmdCheckCargo()
	CmdCheckPrice(commodity model.Commodity, duchyName string)
	CmdCheckWarehouse(planetName string)
	CmdClearEmbargo()
	CmdClearFactory(factoryNo int32)
	CmdClearFavoured()
	CmdClearMilkrun(slotNo int32)
	CmdComms()
	CmdCommsOff()
	CmdCommsOn()
	CmdCommunicate(message string)
	CmdContract(playerName, planetName string, bayNo, value int32)
	CmdCuddle(playerName string)
	CmdCure()
	CmdDeal()
	CmdDeallocate(commodity model.Commodity)
	CmdDeallocateSocialSecurity(points int32)
	CmdDigest1(group model.CommodityGroup)
	CmdDigest2(group model.CommodityGroup, planetName string)
	CmdDisplayCompany(name string)
	CmdDisplayDuchies()
	CmdDisplayDuchy(duchyName string)
	CmdDisplayFactories(planetName string)
	CmdDisplayFactory(factoryNo int32)
	CmdDisplayInformation(project model.Project)
	CmdDisplayPlanet(name string)
	CmdDisplayProduction()
	CmdDisplayProject()
	CmdDisplayRoutes()
	CmdDisplayWarehouses()
	CmdDividend(number int32)
	CmdDrink(name model.Name)
	CmdDrop(objectName model.Name)
	CmdEat(name model.Name)
	CmdEnter()
	CmdExamine(name model.Name)
	CmdExamineSpaceship(subjectName string)
	CmdExpel(sysName string)
	CmdFederation()
	CmdFetch(bayList *BayList)
	CmdFire(weapon int, name *model.Name)
	CmdFit(name model.Name)
	CmdFlog(name string)
	CmdFuck(name model.Name)
	CmdFull()
	CmdGag(playerName string)
	CmdGamble(colorWager model.GambleColour, stake int32)
	CmdGet(objectName model.Name)
	CmdGiveGroats(groats int32, name model.Name)
	CmdGiveObject(name1 model.Name, name2 model.Name)
	CmdGlance()
	CmdGo(direction model.Direction)
	CmdGoto(where string)
	CmdGPS()
	CmdGrope(targetName string)
	CmdHamsters()
	CmdHelp(topic int32, subTopic int32)
	CmdHug(targetName string)
	CmdInstallArmour(number int32)
	CmdInstallComputer(number int32)
	CmdInstallEngines(number int32)
	CmdInstallGun(gunType int32)
	CmdInstallHull(number int32)
	CmdInstallShields(number int32)
	CmdInsure(action model.InsureAction)
	CmdInventory()
	CmdIssue(shares int32)
	CmdJettisonAmmunition()
	CmdJettisonMissile()
	CmdJob()
	CmdJobs()
	CmdJobsOff()
	CmdJobsOn()
	CmdJoin(duchyName string)
	CmdJump(destName string)
	CmdKiss(playerName string)
	CmdKnitBaron(name string)
	CmdKnitExplorer(name string, promo bool)
	CmdKnitNavigator(name string)
	CmdLand()
	CmdLaunch(name model.Name)
	CmdLiquidateCompany()
	CmdLiquidateFactory(factoryNo int32)
	CmdLiquidateWarehouse(planetName string)
	CmdLoad()
	CmdLock(name string)
	CmdLook()
	CmdManual()
	CmdMood(mood string)
	CmdMoodOff()
	CmdNationalize(companyName string)
	CmdNavigate()
	CmdNavigateOff()
	CmdNavigateOn()
	CmdOffer(haulerName, fromPlanetName string, bayNo int32, toPlanetName string, time, carriage int32, toWarehouse bool)
	CmdOfferJob(commodity model.Commodity, toPlanetName string, payment int32)
	CmdOffline()
	CmdOnline(name string)
	CmdOrbit()
	CmdOrder(name string)
	CmdOrderPlanet(name string)
	CmdOrderSpaceship()
	CmdPaintSpaceship(description string)
	CmdPlanet()
	CmdPlay(music string)
	CmdPost(message string)
	CmdPress()
	CmdPressButton0()
	CmdPressButton1(colour model.ButtonColour)
	CmdPullLever()
	CmdPutIntoJig(name model.Name)
	CmdPutIntoSlot(objectName model.Name)
	CmdQuickScore()
	CmdQuickStatus()
	CmdQuickWho()
	CmdQuickWhoChannel(channel int32)
	CmdQuickWhoSystem(sysName string)
	CmdQuit()
	CmdRanks()
	CmdRead()
	CmdRegistry()
	CmdReject()
	CmdRejectFactory()
	CmdRepairComputer()
	CmdRepairEngines()
	CmdRepairGun(gunType int)
	CmdRepairHull()
	CmdRepairShields()
	CmdRepay(amount int32)
	CmdReset()
	CmdReward(bounty int32, villainName string)
	CmdSalute()
	CmdSay(speech string)
	CmdScore()
	CmdSecede()
	CmdSellCargo(bayNo int32)
	CmdSellFactory(factoryNo int32) // FIXME: optional factoryNo
	CmdSellSpaceship()
	CmdSellWarehouse(planetName string)
	CmdSetDuchyTax(newRate int32)
	CmdSetEmbargo(duchyName string)
	CmdSetFavoured(duchyName string)
	CmdSetFavouredTax(newRate int32)
	CmdSetLayoff(number int32)
	CmdSetMarkup(level int32)
	CmdSetMarkupCommodity(commodity model.Commodity, level int32)
	CmdSetMilkrun(slotNo int32, commodity model.Commodity, planetName string, carriage int32)
	CmdSetOutput(delivery model.Delivery)
	CmdSetPlanetTax(newRate int32)
	CmdSetStockpile(commodity model.Commodity, level int32)
	CmdSetTax(rate int32)
	CmdSetWages(number int32)
	CmdShowConfiguration()
	CmdShowProduction()
	CmdShowStatus()
	CmdShuffle(planetName string)
	CmdSign()
	CmdSlap(playerName string)
	CmdSlide()
	CmdSlideShelving()
	CmdSnog(playerName string)
	CmdSnuggle(playerName string)
	CmdSpy(playerName string)
	CmdSpyOff()
	CmdSpynetNotice()
	CmdSpynetReport(name string)
	CmdStatus()
	CmdStore(bayList *BayList)
	CmdSuicide()
	CmdSulk()
	CmdSwitchShields()
	CmdSystems()
	CmdTarget(name string)
	CmdTargetOff()
	CmdTeleport(locNo int32, sysName string)
	CmdTell(playerName string, message string)
	CmdTickle(playerName string)
	CmdTime()
	CmdTimeout(minutes ...int32)
	CmdTimeoutOff()
	CmdTimewarp()
	CmdTorch(planetName string, bayNo int32)
	CmdTour()
	CmdTrace(trace model.Trace)
	CmdTrade()
	CmdTradeGroup(group model.CommodityGroup)
	CmdTransmit(message string)
	CmdTravel(planetName string)
	CmdTune(channel int32)
	CmdTuneOff()
	CmdType(text string)
	CmdUngag(playerName string)
	CmdUnload()
	CmdUnlock(name string)
	CmdUnpost(name string)
	CmdUnravelNavigator(name string)
	CmdUse(objectName model.Name)
	CmdVoid()
	CmdWait()
	CmdWanted()
	CmdWhereIs(name model.Name)
	CmdWho()
	CmdWhoChannel(channel int32)
	CmdWhoSystem(sysName string)
	CmdWhoIsName(subjectName string)
	CmdWhoIsUID(subjectUID ibgames.AccountID)
	CmdWork(duchyName string)
	Name() string
	UnknownCommand()
}
